### ISSUE TITLE
VIQET - can't get results

### ISSUE THREAD

**Issue by pzorea** [VIQET/VIQET-Desktop#2]
Hi there,
I'm tring to use the tool. 
I met all the requirements (PC system & test material instructions).
I ran all the process but at the end I all final scores are N/A.
see the screenshot:
![image](https://cloud.githubusercontent.com/assets/6675973/12513347/15d5f4a6-c126-11e5-8316-c3478b3f445a.png)

Thanks,
Pini.

**Comment by rkalidin** [comment]
Hi Pini,

Thanks for using VIQET and reporting the error. 
I see that you are using Windows 10. Can you let us know which edition of Windows 10 you are using?
We are currently working on resolving the issue and expect to release an update by early next week.  

Thank you,
Rohit

**Comment by pzorea** [comment]
Hi Rohit,
Thanks for your prompt respond.
I have Win 10 ver. 1511.
I just found your tool in last week and it's very interesting...since in my
research in IQA,
I would suggest to add to your tool the option of calibrate/tune the
default parameters for IQA...I guess it's possible only via the source code.
The idea is to calibrate those parameters according to results of real
human view tests.
Thanks and Best Regards'
Pini.

2016-01-23 0:53 GMT+02:00 rkalidin notifications@github.com:

**Comment by rkalidin** [comment]
Hi Pini,

Thanks for providing the version number.
We fixed the issue and pushed the changes to the application today. Please install VIQET from the url below and let us know if you have any trouble running VIQET.
https://github.com/VIQET/VIQET-Desktop/releases
Again thanks for the feedback.

Rohit

**Comment by pzorea** [comment]
Thanks a lot.....it's working.
Thanks and Best Regards,
Pini.

2016-01-26 4:11 GMT+02:00 rkalidin notifications@github.com:

**Comment by rkalidin** [comment]
Hi Pini,

An updated version of VIQET is now available. It fixes a bug introduced in the recent patch. An Android app is also now available and can be downloaded from the App Store link below
https://play.google.com/store/apps/details?id=org.vqeg.viqet&hl=en

Rohit

**Comment by pzorea** [comment]
Thanks a lot Rohit.
Best Regards'
Pini.

2016-03-02 1:27 GMT+02:00 rkalidin notifications@github.com:

**Comment by pzorea** [comment]
Dear Rohit,
I'm using the VIQET for my research on Image Quality (great tool !!!) and I found that the MOS given by the tool does't meet my IQ opinion. 
In order to continue of your tool calibration I need your support on the following requests:
1. I need a version that get only 5 images (created from one original image, but different IQ attributes).
2. Please let me know how to change the weight of each IQ attributes the uses for image analysis.my objective is to tune the tool in order to get my opinion on IQ.
Thanks and Best Regards,
Pini.

**Comment by rkalidin** [comment]
Hi Pini,

Thank you for the feedback! Would you be able to share any additional details on the kind of images where you are seeing a difference between VIQET predicted MOS and your visual IQ assessment? If you could share a few sample images, that would be very helpful.
Regarding the additional requriments you requested, we are looking into how we can support them and will get back to you as soon as possible. Addtionally, would you be available for a conference call to better understand your requirements.

Thanks,
Rohit

**Comment by pzorea** [comment]
Dear Rohit,
Thanks for your prompt respond.
Please find in attached 5 images, the"Contrast" and "Sharpness" received
the highest score by 35 observers in HVT.
The "Brightness" received the lowest score.
Regarding conference call, we can talk over "Whatsup" my mobile number is:
+972542403586.
We can talk tomorrow after 21:00PM (Israel time, GMT+2).
Best Regards,
Pini.

2016-05-26 22:11 GMT+03:00 rkalidin notifications@github.com:

**Comment by rkalidin** [comment]
Would you be able to send an email with the 5 images to michele.a.saad@intel.com (VIME co-chair)
I was not able to find the images on your previous post.
Also can we schedule the call on Tuesday (May 31st)?

Thanks,
Rohit

**Comment by pzorea** [comment]
Done.
Yes, we can talk on Tuesday. what is your time zone?

2016-05-27 1:44 GMT+03:00 rkalidin notifications@github.com:

**Comment by pzorea** [comment]
In the meantime before we talk, I was thinking about new feature to make
VIQET much more powerful.
here is my request:
1. I would suggest to add "Calibration" option in the main menu and when
user selects this option a new window opened
    with sliders for each IQ, so user can move the slider (Right or Left)
in order to change the weight of IQ feature for the
tool when rating image.

2016-05-27 7:59 GMT+03:00 Pini Zorea pini.zorea@gmail.com:

**Comment by pzorea** [comment]
In the meantime before we talk, I was thinking about new feature to make
VIQET much more powerful.
here is my request:
1. I would suggest to add "Calibration" option in the main menu and when
user selects this option a new window opened
    with sliders for each IQ, so user can move the slider (Right or Left)
in order to change the weight of IQ feature for the
    tool when rating image and also add "check box" for "save as default"
and "load default".
2. To add new feature of "White Balance error" displaying the actual RGB
shift from pure White.

Best Regards,
Pini.

2016-05-27 22:48 GMT+03:00 Pini Zorea pini.zorea@gmail.com:

**Comment by rkalidin** [comment]
Our time zone is PDT (GMT - 7hrs). 
What is a good time to call you? We are available from 10AM to 3PM PDT on week days. 

Thanks,
Rohit

**Comment by pzorea** [comment]
I'm out now... I'll send you email as l'm back... about 3h from now.
בתאריך 31 במאי 2016 21:19,‏ "rkalidin" notifications@github.com כתב:

**Comment by pzorea** [comment]
I'm available for call my number: +972542403586.

2016-05-31 21:30 GMT+03:00 Pini Zorea pini.zorea@gmail.com:

**Comment by pzorea** [comment]
I'll be available tomorrow (Wed.) from 10AM PDT, please call my mobile
phone: +972-54-2403586  or Skype (Pini Zorea).

2016-05-31 21:19 GMT+03:00 rkalidin notifications@github.com:

**Comment by rkalidin** [comment]
Ok. I will call you tomorrow (Wednesday) at 1pm(PDT). Sorry for the late reply.

**Comment by pzorea** [comment]
Thanks.
בתאריך 1 ביוני 2016 01:47,‏ "rkalidin" notifications@github.com כתב:

**Comment by pzorea** [comment]
Waiting for your call.
בתאריך 1 ביוני 2016 09:00,‏ "Pini Zorea" pini.zorea@gmail.com כתב:

**Comment by Armendariz777** [comment]
El programa no  abre en Windows 10 pro 22H2, alguien sabe porque.
